device: cuda

dir:
  root: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/HiCInterpolate
  model_state: ${dir.root}/models
  output: ${dir.root}/output
  data: /home/hc0783.unt.ad.unt.edu/workspace/hic_interpolation/data/triplets/kr_log_clip_norm
  image: ${dir.data}/${data.patch}

file:
  train: ${dir.image}/train.txt
  test: ${dir.image}/test.txt
  vgg_model: ${dir.data}/models/imagenet-vgg-verydeep-19.mat
  snapshot: ${dir.model_state}/${model.name}_snapshot.pt
  model: ${dir.model_state}/${model.name}.pt
  train_val_plot: ${dir.output}/${model.name}_train_val_plot.png
  test_hic_map: ${dir.output}/${model.name}_hic_map.jpg
  eval_metrics: ${dir.output}/${model.name}_val_metrics.csv
  psnr_eval_plot: ${dir.output}/${model.name}_psnr_plot.png
  ssim_eval_plot: ${dir.output}/${model.name}_ssim_plot.png
  ncc_eval_plot: ${dir.output}/${model.name}_ncc_plot.png
  lpips_eval_plot: ${dir.output}/${model.name}_lpips_plot.png
  eval_plot: ${dir.output}/${model.name}_eval_plot.png
  lr_plot: ${dir.output}/${model.name}_lr_plot.png
  log: ${dir.output}/${model.name}.log

data:
  patch: 256
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_ratio: [0.20, 0.05]
  batch_size: 8

training:
  epochs: 300
  save_every: 10
  learning_rate: 0.1e-4
  decay_steps: 100
  decay_rate: 0.631
  lr_staircase: true

model:
  name: hicinterpolate_${data.patch}
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 6
  ext_feature_level: 4
  unique_levels: 3
  flow:
    num_of_convs: [3, 3, 3, 3, 3, 3]
    out_channels: [8, 16, 32, 64, 128, 256]
  fusion_pyramid_level: 5

loss:
  weight_parameters:
    - name: mse
      boundaries: [0]
      values: [1.0, 1.0]
    - name: vgg
      boundaries: [150]
      values: [0.3, 0.7]
    - name: genome_disco
      boundaries: [0]
      values: [1.0, 1.0]
    # - name: tv
    #   boundaries: [0]
    #   values: [1.0, 1.0]

eval:
  num_visualization_samples: 2