device: cuda

paths:
  root_dir: /home/mohit/Documents/project/interpolation/HiCInterpolate
  data_dir: /home/mohit/Documents/project/interpolation/data/triplets/normalized
  record_file: ${paths.data_dir}/64/train.txt
  image_dir: ${paths.data_dir}/64
  vgg_model_file: ${paths.data_dir}/models/imagenet-vgg-verydeep-19.mat

  model_file: ${paths.root_dir}/models/${model.name}.pth
  model_state_dir: ${paths.root_dir}/models

  output_dir: ${paths.root_dir}/output
  img_val_plot_path: ${paths.output_dir}
  train_val_plot_file: ${paths.output_dir}/${model.name}_train_val_plot.png
  test_plot_file: ${paths.output_dir}/${model.name}_test_plot.png
  eval_metrics_file: ${paths.output_dir}/${model.name}_val_metrics.csv
  psnr_eval_plot_file: ${paths.output_dir}/${model.name}_psnr_plot.png
  ssim_eval_plot_file: ${paths.output_dir}/${model.name}_ssim_plot.png
  lr_file: ${paths.output_dir}/${model.name}_lr_plot.png

data:
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_ratio: [0.85, 0.15]
  batch_size: 32

training:
  epochs: 1000
  save_every: 10
  learning_rate: 0.0001
  decay_steps: 50
  decay_rate: 0.95
  lr_staircase: true

model:
  name: hicinterpolate_test
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 4
  ext_feature_level: 3
  unique_levels: 2
  flow:
    num_of_convs: [3, 3, 3]
    out_channels: [16, 32, 64]
  fusion_pyramid_level: 4

loss:
  weight_parameters:
    - name: charbonnier
      boundaries: [0]
      values: [1.0, 1.0]
    - name: ssim
      boundaries: [0]
      values: [1.0, 1.0]
    - name: vgg
      boundaries: [600]
      values: [1.0, 0.40]
    - name: style
      boundaries: [400]
      values: [0.0, 0.60]
    - name: symmetry
      boundaries: [0]
      values: [1.0, 1.0]

eval:
  num_visualization_samples: 2