device: cuda

dir:
  root: /home/hchowdhu/Documents/HiCInterpolate
  model_state: ${dir.root}/models
  output: ${dir.root}/output
  data: /mmfs1/home/hchowdhu/data/hic_triplets/normalized
  image: ${dir.data}/${data.patch}

file:
  train: ${dir.image}/train.txt
  test: ${dir.image}/test.txt
  vgg_model: ${dir.data}/models/imagenet-vgg-verydeep-19.mat
  snapshot: ${dir.model_state}/${model.name}_snapshot.pt
  model: ${dir.model_state}/${model.name}.pt
  train_val_plot: ${dir.output}/${model.name}_train_val_plot.png
  test_hic_map: ${dir.output}/${model.name}_hic_map.jpg
  eval_metrics: ${dir.output}/${model.name}_val_metrics.csv
  psnr_eval_plot: ${dir.output}/${model.name}_psnr_plot.png
  ssim_eval_plot: ${dir.output}/${model.name}_ssim_plot.png
  lr_plot: ${dir.output}/${model.name}_lr_plot.png
  log: ${dir.output}/${model.name}.log

data:
  patch: 64
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_ratio: [0.85, 0.15]
  batch_size: 32

training:
  epochs: 1000
  save_every: 10
  learning_rate: 0.0001
  decay_steps: 50
  decay_rate: 0.794
  lr_staircase: true

model:
  name: hicinterpolate_${data.patch}
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 4
  ext_feature_level: 3
  unique_levels: 2
  flow:
    num_of_convs: [3, 5, 5]
    out_channels: [16, 32, 64]
  fusion_pyramid_level: 4

loss:
  weight_parameters:
    - name: mse
      boundaries: [0]
      values: [1.0, 1.0]
    - name: ssim
      boundaries: [0]
      values: [1.0, 1.0]
    - name: vgg
      boundaries: [500]
      values: [1.0, 0.80]
    - name: style
      boundaries: [500]
      values: [0.0, 1.00]
    - name: symmetry
      boundaries: [0]
      values: [1.0, 1.0]
eval:
  num_visualization_samples: 2