device: cuda

dir:
  root: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/HiCInterpolate
  model_state: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/output/log_mm_triplets_dataset
  output: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/output/log_mm_triplets_dataset
  data: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset
  image: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset


file:
  dataset_dict: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset/train_5000_128.txt
  snapshot: ${dir.model_state}/${model.name}_p${data.patch}_b${data.batch_size}_snapshot.pt
  model: ${dir.model_state}/${model.name}_p${data.patch}_b${data.batch_size}.pt
  test_hic_map: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_hic_map.jpg
  num_visualization_samples: 2
  val_metrics: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_val_metrics.csv
  ssim_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_ssim_plot.png
  genome_disco_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_genome_disco_plot.png
  train_val_loss_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_train_val_loss_plot.png
  hicrep_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_hicrep_plot.png
  lr_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_lr_plot.png
  log: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}.log
  val_metrics_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_val_metrics.png

data:
  patch: 128
  batch_size: 20
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_test_ratio: [0.2, 0.025, 0.025]

training:
  epochs: 100
  restart_every: 100
  save_every: 10
  lr: 2e-4
  min_lr: 1e-5
  decay_steps: 100
  decay_rate: 0.215
  lr_staircase: true

model:
  name: hicinterpolate_${data.patch}
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 4
  ext_feature_level: 3
  unique_levels: 2
  flow:
    num_of_convs: [7, 5, 7]
    out_channels: [16, 32, 64]
  fusion_pyramid_level: 4

loss:
  weight_parameters:
    - name: awl
      boundaries: [0]
      values: [1.0, 1.0]
    - name: ms_ssim
      boundaries: [0]
      values: [0.25, 0.25]
    - name: tv
      boundaries: [0]
      values: [1e-4, 1e-4]
