device: cuda

dir:
  root: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/HiCInterpolate
  model_state: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/output/log_mm_triplets_dataset
  output: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/output/log_mm_triplets_dataset
  data: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset
  image: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset


file:
  dataset_dict: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/log_mm_triplets_dataset/train_10000_64.txt
  snapshot: ${dir.model_state}/${model.name}_p${data.patch}_b${data.batch_size}_snapshot.pt
  model: ${dir.model_state}/${model.name}_p${data.patch}_b${data.batch_size}.pt
  test_hic_map: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_hic_map.jpg
  num_visualization_samples: 2
  val_metrics: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_val_metrics.csv
  ssim_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_ssim_plot.png
  genome_disco_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_genome_disco_plot.png
  train_val_loss_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_train_val_loss_plot.png
  hicrep_val_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_hicrep_plot.png
  lr_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_lr_plot.png
  log: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}.log
  val_metrics_plot: ${dir.output}/${model.name}_p${data.patch}_b${data.batch_size}_val_metrics.png

data:
  patch: 64
  batch_size: 64
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_test_ratio: [0.2, 0.0125, 0.0125]

training:
  epochs: 500
  restart_every: 100
  save_every: 10
  lr: 1e-3
  min_lr: 1e-5
  decay_steps: 100
  decay_rate: 0.215
  lr_staircase: true
  adv_weight: 0.05
  adv_start_epoch: 150
  d_lr: 1e-4
  gan_in_channels: 3

model:
  name: hicinterpolate_${data.patch}
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 4
  ext_feature_level: 3
  unique_levels: 2
  flow:
    num_of_convs: [7, 5, 7]
    out_channels: [16, 32, 64]
  fusion_pyramid_level: 4

loss:
  weight_parameters:
    - name: charbonnier
      boundaries: [150]
      values: [1.0, 1.0]
    - name: mse
      boundaries: [150]
      values: [0.1, 0.1]
    - name: ms_ssim
      boundaries: [150]
      values: [1.0, 1.0]
    - name: ffl
      boundaries: [150]
      values: [1.0, 1.0]
    - name: stratum
      boundaries: [150]
      values: [1.0, 1.0]
    - name: grad
      boundaries: [150]
      values: [0.5, 0.5]
    - name: vgg
      boundaries: [150]
      values: [0.05, 0.1]
    - name: symmetry
      boundaries: [150]
      values: [1.0, 1.0]
    - name: tv
      boundaries: [150]
      values: [0.01, 0.01]
