device: cuda

dir:
  root: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/HiCInterpolate
  model_state: /tmp/hic_test/model_state
  output: /tmp/hic_test/output
  data: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/mm_triplets_dataset
  image: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/mm_triplets_dataset

file:
  dataset_dict: /home/hc0783@unt.ad.unt.edu/workspace/hicinterpolate/datasets/mm_triplets_dataset/train_10000_64.txt
  snapshot: ${dir.model_state}/hicinterpolate_test_snapshot.pt
  model: ${dir.model_state}/hicinterpolate_test.pt
  val_metrics: ${dir.output}/hicinterpolate_test_metrics.csv
  train_val_loss_plot: ${dir.output}/hicinterpolate_test_loss_plot.png
  log: ${dir.output}/hicinterpolate_test.log

data:
  patch: 64
  batch_size: 8
  interpolator_images_map:
    frame_0: img1.npy
    frame_1: img2.npy
    frame_2: img3.npy
  train_val_test_ratio: [0.7, 0.15, 0.15]

training:
  epochs: 5
  save_every: 2
  init_lr: 1e-4
  min_lr: 1e-6
  weight_decay: 1e-4

model:
  name: hicinterpolate_test
  init_in_channels: 1
  init_out_channels: 4
  pyramid_level: 3
  ext_feature_level: 2
  unique_levels: 1
  flow:
    num_of_convs: [5, 3]
    out_channels: [16, 32]
  fusion_pyramid_level: 3

loss:
  weight_parameters:
    - name: mse
      boundaries: []
      values: [1.0]
    - name: symmetry
      boundaries: []
      values: [0.5]
